// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Get candles
    ///
    /// Get candles for specified market and resolution.
    ///
    /// **Modes:**
    /// - **Time range:** provide `start_ts` and `end_ts` to get candles in [start_ts, end_ts).
    /// - **Last N candles:** provide `limit` (number of candles). They are counted backwards from `end_ts`;
    ///   if `end_ts` is omitted, `end_ts` is treated as current time (now).
    ///
    /// **Validation (400 if violated):**
    /// - Either `limit` or both `start_ts` and `end_ts` must be provided.
    /// - If `limit` is set, it must be a positive number.
    /// - If both `start_ts` and `end_ts` are set, `start_ts` must be less than or equal to `end_ts`.
    ///
    /// **Limits:** Number of candles (from time range or `limit`) must not exceed 3000. Exceeding returns 400.
    ///
    ///
    /// - Remark: HTTP `POST /kandelabr/public-api/v1/candles`.
    /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)`.
    func getCandles(_ input: Operations.getCandles.Input) async throws -> Operations.getCandles.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Get candles
    ///
    /// Get candles for specified market and resolution.
    ///
    /// **Modes:**
    /// - **Time range:** provide `start_ts` and `end_ts` to get candles in [start_ts, end_ts).
    /// - **Last N candles:** provide `limit` (number of candles). They are counted backwards from `end_ts`;
    ///   if `end_ts` is omitted, `end_ts` is treated as current time (now).
    ///
    /// **Validation (400 if violated):**
    /// - Either `limit` or both `start_ts` and `end_ts` must be provided.
    /// - If `limit` is set, it must be a positive number.
    /// - If both `start_ts` and `end_ts` are set, `start_ts` must be less than or equal to `end_ts`.
    ///
    /// **Limits:** Number of candles (from time range or `limit`) must not exceed 3000. Exceeding returns 400.
    ///
    ///
    /// - Remark: HTTP `POST /kandelabr/public-api/v1/candles`.
    /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)`.
    public func getCandles(
        headers: Operations.getCandles.Input.Headers = .init(),
        body: Operations.getCandles.Input.Body
    ) async throws -> Operations.getCandles.Output {
        try await getCandles(Operations.getCandles.Input(
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    ///
    /// - Parameters:
    ///   - host:
    public static func server1(host: Swift.String = "api.example.com") throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://{host}",
            variables: [
                .init(
                    name: "host",
                    value: host
                )
            ]
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/GetCandlesRequest`.
        public struct GetCandlesRequest: Codable, Hashable, Sendable {
            /// Ticker symbol. Two forms are accepted:
            ///   - `ASSET/CURRENCY` (e.g. `BTC/USD`) — instrument defaults to PERP.
            ///   - `ASSET/CURRENCY/INSTRUMENT` (e.g. `BTC/USDT/SPOT`) — full form.
            ///
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/ticker`.
            public var ticker: Swift.String
            /// Candle resolution
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/resolution`.
            @frozen public enum resolutionPayload: String, Codable, Hashable, Sendable {
                case _1m = "1m"
                case _5m = "5m"
                case _15m = "15m"
                case _30m = "30m"
                case _1h = "1h"
                case _4h = "4h"
                case _1d = "1d"
                case _1w = "1w"
                case _1mo = "1mo"
            }
            /// Candle resolution
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/resolution`.
            public var resolution: Components.Schemas.GetCandlesRequest.resolutionPayload
            /// Start timestamp in milliseconds. Required when not using limit.
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/start_ts`.
            public var start_ts: Swift.Int64?
            /// End timestamp in milliseconds (exclusive). When using limit, candles are counted backwards from this time; if omitted, current time is used.
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/end_ts`.
            public var end_ts: Swift.Int64?
            /// Number of candles to return (positive). When set, candles are counted backwards from end_ts (or now if end_ts omitted).
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesRequest/limit`.
            public var limit: Swift.Int32?
            /// Creates a new `GetCandlesRequest`.
            ///
            /// - Parameters:
            ///   - ticker: Ticker symbol. Two forms are accepted:
            ///   - resolution: Candle resolution
            ///   - start_ts: Start timestamp in milliseconds. Required when not using limit.
            ///   - end_ts: End timestamp in milliseconds (exclusive). When using limit, candles are counted backwards from this time; if omitted, current time is used.
            ///   - limit: Number of candles to return (positive). When set, candles are counted backwards from end_ts (or now if end_ts omitted).
            public init(
                ticker: Swift.String,
                resolution: Components.Schemas.GetCandlesRequest.resolutionPayload,
                start_ts: Swift.Int64? = nil,
                end_ts: Swift.Int64? = nil,
                limit: Swift.Int32? = nil
            ) {
                self.ticker = ticker
                self.resolution = resolution
                self.start_ts = start_ts
                self.end_ts = end_ts
                self.limit = limit
            }
            public enum CodingKeys: String, CodingKey {
                case ticker
                case resolution
                case start_ts
                case end_ts
                case limit
            }
        }
        /// - Remark: Generated from `#/components/schemas/GetCandlesResponse`.
        public struct GetCandlesResponse: Codable, Hashable, Sendable {
            /// Ticker symbol
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesResponse/ticker`.
            public var ticker: Swift.String
            /// Candle resolution
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesResponse/resolution`.
            public var resolution: Swift.String
            /// Start timestamp in milliseconds
            ///
            /// - Remark: Generated from `#/components/schemas/GetCandlesResponse/start_ts`.
            public var start_ts: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/GetCandlesResponse/candles`.
            public var candles: [Components.Schemas.Candle]
            /// Creates a new `GetCandlesResponse`.
            ///
            /// - Parameters:
            ///   - ticker: Ticker symbol
            ///   - resolution: Candle resolution
            ///   - start_ts: Start timestamp in milliseconds
            ///   - candles:
            public init(
                ticker: Swift.String,
                resolution: Swift.String,
                start_ts: Swift.Int64,
                candles: [Components.Schemas.Candle]
            ) {
                self.ticker = ticker
                self.resolution = resolution
                self.start_ts = start_ts
                self.candles = candles
            }
            public enum CodingKeys: String, CodingKey {
                case ticker
                case resolution
                case start_ts
                case candles
            }
        }
        /// - Remark: Generated from `#/components/schemas/Candle`.
        public struct Candle: Codable, Hashable, Sendable {
            /// Open price
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/o`.
            public var o: Swift.String?
            /// High price
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/h`.
            public var h: Swift.String?
            /// Low price
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/l`.
            public var l: Swift.String?
            /// Close price
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/c`.
            public var c: Swift.String?
            /// Volume
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/v`.
            public var v: Swift.String?
            /// Whether the candle is empty (no trades in the period)
            ///
            /// - Remark: Generated from `#/components/schemas/Candle/empty`.
            public var empty: Swift.Bool?
            /// Creates a new `Candle`.
            ///
            /// - Parameters:
            ///   - o: Open price
            ///   - h: High price
            ///   - l: Low price
            ///   - c: Close price
            ///   - v: Volume
            ///   - empty: Whether the candle is empty (no trades in the period)
            public init(
                o: Swift.String? = nil,
                h: Swift.String? = nil,
                l: Swift.String? = nil,
                c: Swift.String? = nil,
                v: Swift.String? = nil,
                empty: Swift.Bool? = nil
            ) {
                self.o = o
                self.h = h
                self.l = l
                self.c = c
                self.v = v
                self.empty = empty
            }
            public enum CodingKeys: String, CodingKey {
                case o
                case h
                case l
                case c
                case v
                case empty
            }
        }
        /// - Remark: Generated from `#/components/schemas/Error`.
        public struct _Error: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Error/status`.
            @frozen public enum statusPayload: String, Codable, Hashable, Sendable {
                case NOT_FOUND = "NOT_FOUND"
                case INVALID_REQUEST = "INVALID_REQUEST"
            }
            /// - Remark: Generated from `#/components/schemas/Error/status`.
            public var status: Components.Schemas._Error.statusPayload
            /// - Remark: Generated from `#/components/schemas/Error/message`.
            public var message: Swift.String
            /// Creates a new `_Error`.
            ///
            /// - Parameters:
            ///   - status:
            ///   - message:
            public init(
                status: Components.Schemas._Error.statusPayload,
                message: Swift.String
            ) {
                self.status = status
                self.message = message
            }
            public enum CodingKeys: String, CodingKey {
                case status
                case message
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Get candles
    ///
    /// Get candles for specified market and resolution.
    ///
    /// **Modes:**
    /// - **Time range:** provide `start_ts` and `end_ts` to get candles in [start_ts, end_ts).
    /// - **Last N candles:** provide `limit` (number of candles). They are counted backwards from `end_ts`;
    ///   if `end_ts` is omitted, `end_ts` is treated as current time (now).
    ///
    /// **Validation (400 if violated):**
    /// - Either `limit` or both `start_ts` and `end_ts` must be provided.
    /// - If `limit` is set, it must be a positive number.
    /// - If both `start_ts` and `end_ts` are set, `start_ts` must be less than or equal to `end_ts`.
    ///
    /// **Limits:** Number of candles (from time range or `limit`) must not exceed 3000. Exceeding returns 400.
    ///
    ///
    /// - Remark: HTTP `POST /kandelabr/public-api/v1/candles`.
    /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)`.
    public enum getCandles {
        public static let id: Swift.String = "getCandles"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getCandles.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getCandles.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.getCandles.Input.Headers
            /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.GetCandlesRequest)
            }
            public var body: Operations.getCandles.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.getCandles.Input.Headers = .init(),
                body: Operations.getCandles.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.GetCandlesResponse)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.GetCandlesResponse {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.getCandles.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.getCandles.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Candles retrieved successfully
            ///
            /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.getCandles.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.getCandles.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/400/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/400/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.getCandles.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.getCandles.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// Invalid request
            ///
            /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.getCandles.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            public var badRequest: Operations.getCandles.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            public struct NotFound: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/404/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/404/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.getCandles.Output.NotFound.Body
                /// Creates a new `NotFound`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.getCandles.Output.NotFound.Body) {
                    self.body = body
                }
            }
            /// Ticker not found
            ///
            /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.getCandles.Output.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Operations.getCandles.Output.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            public struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/500/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/kandelabr/public-api/v1/candles/POST/responses/500/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.getCandles.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.getCandles.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal error
            ///
            /// - Remark: Generated from `#/paths//kandelabr/public-api/v1/candles/post(getCandles)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.getCandles.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            public var internalServerError: Operations.getCandles.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
