//
// DepositClickOnrampContinue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User tapped &#39;Continue&#39; on the Insert_amount screen, proceeding to the provider flow (Figma: Provider_flow) */
public struct DepositClickOnrampContinue: Codable, JSONEncodable, Hashable {

    public enum BuyAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public var eventName: String = "deposit_click_onramp_continue"
    /** Asset the user intends to buy, in chain:type:symbol format (same value as in deposit_click_buy event) */
    public var buyAsset: BuyAsset
    /** Name of the onramp provider */
    public var providerName: String
    /** Amount the user intends to buy */
    public var buyAmount: Float

    public init(eventName: String = "deposit_click_onramp_continue", buyAsset: BuyAsset, providerName: String, buyAmount: Float) {
        self.eventName = eventName
        self.buyAsset = buyAsset
        self.providerName = providerName
        self.buyAmount = buyAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case buyAsset = "buy_asset"
        case providerName = "provider_name"
        case buyAmount = "buy_amount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(buyAsset, forKey: .buyAsset)
        try container.encode(providerName, forKey: .providerName)
        try container.encode(buyAmount, forKey: .buyAmount)
    }
}


