//
// DepositViewC2c.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User sees the crypto-to-crypto purchase screen. Figma: Buy_ton_with_crypto / Send_token (for TON), or Stablecoin / Send_asset (for USDT)  */
public struct DepositViewC2c: Codable, JSONEncodable, Hashable {

    public enum BuyAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public static let sellAssetRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[a-z0-9]+:[a-z0-9]+:[A-Z0-9]+$/")
    public var eventName: String = "deposit_view_c2c"
    /** Asset the user intends to buy, in chain:type:symbol format (same value as in deposit_click_buy event) */
    public var buyAsset: BuyAsset
    /** Asset the user sells, in chain:type:symbol format (e.g. ton:jetton:USDT, ton:native:TON) */
    public var sellAsset: String

    public init(eventName: String = "deposit_view_c2c", buyAsset: BuyAsset, sellAsset: String) {
        self.eventName = eventName
        self.buyAsset = buyAsset
        self.sellAsset = sellAsset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case buyAsset = "buy_asset"
        case sellAsset = "sell_asset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(buyAsset, forKey: .buyAsset)
        try container.encode(sellAsset, forKey: .sellAsset)
    }
}


