//
// DepositClickBuy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User tapped a buy option on the Deposit screen (Figma: Deposit with Cash or Crypto) */
public struct DepositClickBuy: Codable, JSONEncodable, Hashable {

    public enum BuyAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public var eventName: String = "deposit_click_buy"
    /** Asset the user intends to buy, in chain:type:symbol format */
    public var buyAsset: BuyAsset

    public init(eventName: String = "deposit_click_buy", buyAsset: BuyAsset) {
        self.eventName = eventName
        self.buyAsset = buyAsset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case buyAsset = "buy_asset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(buyAsset, forKey: .buyAsset)
    }
}


