//
// DepositViewP2p.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User sees the P2P market screen (Figma: Wallet_flow) */
public struct DepositViewP2p: Codable, JSONEncodable, Hashable {

    public enum BuyAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public enum SellAsset: String, Codable, CaseIterable {
        case fiat = "fiat"
    }
    public var eventName: String = "deposit_view_p2p"
    /** Asset the user intends to buy, in chain:type:symbol format (same value as in deposit_click_buy event) */
    public var buyAsset: BuyAsset
    /** Asset the user sells */
    public var sellAsset: SellAsset = .fiat

    public init(eventName: String = "deposit_view_p2p", buyAsset: BuyAsset, sellAsset: SellAsset = .fiat) {
        self.eventName = eventName
        self.buyAsset = buyAsset
        self.sellAsset = sellAsset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case buyAsset = "buy_asset"
        case sellAsset = "sell_asset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(buyAsset, forKey: .buyAsset)
        try container.encode(sellAsset, forKey: .sellAsset)
    }
}


