//
// WithdrawClickOnrampContinue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User tapped &#39;Continue&#39; on the Insert_amount screen, proceeding to the provider flow (Figma: Provider_flow) */
public struct WithdrawClickOnrampContinue: Codable, JSONEncodable, Hashable {

    public enum SellAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public var eventName: String = "withdraw_click_onramp_continue"
    /** Asset the user intends to sell, in chain:type:symbol format (same value as in withdraw_click_sell event) */
    public var sellAsset: SellAsset
    /** Name of the onramp provider */
    public var providerName: String
    /** Amount the user intends to sell */
    public var sellAmount: Float

    public init(eventName: String = "withdraw_click_onramp_continue", sellAsset: SellAsset, providerName: String, sellAmount: Float) {
        self.eventName = eventName
        self.sellAsset = sellAsset
        self.providerName = providerName
        self.sellAmount = sellAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case sellAsset = "sell_asset"
        case providerName = "provider_name"
        case sellAmount = "sell_amount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(sellAsset, forKey: .sellAsset)
        try container.encode(providerName, forKey: .providerName)
        try container.encode(sellAmount, forKey: .sellAmount)
    }
}


