//
// WithdrawViewP2p.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User sees the P2P market screen */
public struct WithdrawViewP2p: Codable, JSONEncodable, Hashable {

    public enum SellAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public enum BuyAsset: String, Codable, CaseIterable {
        case fiat = "fiat"
    }
    public var eventName: String = "withdraw_view_p2p"
    /** Asset the user intends to sell, in chain:type:symbol format (same value as in withdraw_click_sell event) */
    public var sellAsset: SellAsset
    /** Asset the user receives */
    public var buyAsset: BuyAsset = .fiat

    public init(eventName: String = "withdraw_view_p2p", sellAsset: SellAsset, buyAsset: BuyAsset = .fiat) {
        self.eventName = eventName
        self.sellAsset = sellAsset
        self.buyAsset = buyAsset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case sellAsset = "sell_asset"
        case buyAsset = "buy_asset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(sellAsset, forKey: .sellAsset)
        try container.encode(buyAsset, forKey: .buyAsset)
    }
}


