//
// WithdrawClickSell.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User tapped an asset to sell on the Withdraw screen */
public struct WithdrawClickSell: Codable, JSONEncodable, Hashable {

    public enum From: String, Codable, CaseIterable {
        case walletScreen = "wallet_screen"
        case jettonScreen = "jetton_screen"
        case deepLink = "deep_link"
        case tonconnectLocal = "tonconnect_local"
        case tonconnectRemote = "tonconnect_remote"
        case qrCode = "qr_code"
    }
    public enum SellAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public var eventName: String = "withdraw_click_sell"
    /** Source location where withdraw was opened (same value as in withdraw_open event) */
    public var from: From
    /** Asset the user intends to sell, in chain:type:symbol format */
    public var sellAsset: SellAsset

    public init(eventName: String = "withdraw_click_sell", from: From, sellAsset: SellAsset) {
        self.eventName = eventName
        self.from = from
        self.sellAsset = sellAsset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case from
        case sellAsset = "sell_asset"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(from, forKey: .from)
        try container.encode(sellAsset, forKey: .sellAsset)
    }
}


