//
// WithdrawViewOnrampFlow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
// Schema version: 2.8.2
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** User is presented with the provider&#39;s flow (Figma: Provider_flow). tx_id is the transaction ID generated by Tonkeeper for this withdrawal attempt, used to join clickstream data with onramp API data.  */
public struct WithdrawViewOnrampFlow: Codable, JSONEncodable, Hashable {

    public enum SellAsset: String, Codable, CaseIterable {
        case tonNativeTon = "ton/mainnet/coin"
        case tonJettonUsdt = "ton/mainnet/jetton/0:b113a994b5024a16719f69139328eb759596c38a25f59028b146fecdc3621dfe"
        case tronTrc20Usdt = "tron/mainnet/trc20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
    }
    public enum BuyAsset: String, Codable, CaseIterable {
        case fiat = "fiat"
    }
    public var eventName: String = "withdraw_view_onramp_flow"
    /** Asset the user intends to sell, in chain:type:symbol format (same value as in withdraw_click_sell event) */
    public var sellAsset: SellAsset
    /** Name of the onramp provider */
    public var providerName: String
    /** Amount the user intends to sell (same value as in withdraw_click_onramp_continue event) */
    public var sellAmount: Float
    /** Asset the user receives */
    public var buyAsset: BuyAsset = .fiat
    /** Tonkeeper-generated transaction ID for this withdrawal attempt, used to join clickstream data with onramp API data */
    public var txId: String

    public init(eventName: String = "withdraw_view_onramp_flow", sellAsset: SellAsset, providerName: String, sellAmount: Float, buyAsset: BuyAsset = .fiat, txId: String) {
        self.eventName = eventName
        self.sellAsset = sellAsset
        self.providerName = providerName
        self.sellAmount = sellAmount
        self.buyAsset = buyAsset
        self.txId = txId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventName
        case sellAsset = "sell_asset"
        case providerName = "provider_name"
        case sellAmount = "sell_amount"
        case buyAsset = "buy_asset"
        case txId = "tx_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(sellAsset, forKey: .sellAsset)
        try container.encode(providerName, forKey: .providerName)
        try container.encode(sellAmount, forKey: .sellAmount)
        try container.encode(buyAsset, forKey: .buyAsset)
        try container.encode(txId, forKey: .txId)
    }
}


